name: aegean-archive

services:
  database:
    image: mariadb:11.4
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "photo_archive"
      MYSQL_USER: "aegean"
      MYSQL_PASSWORD: "aegean"

    ports:
      - "3307:3306"

    volumes:
      - mariadb-data:/var/lib/mysql

    networks:
      - aegean-network

    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  app1:
    build: .
    restart: unless-stopped

    depends_on:
      database:
        condition: service_healthy

    environment:
      INSTANCE_NAME: "app1"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_NAME: "photo_archive"
      DB_USER: "aegean"
      DB_PASSWORD: "aegean"
      PYTHONUNBUFFERED: "1"

    ports:
      - "5001:5000"

    networks:
      - aegean-network

  app2:
    build: .
    restart: unless-stopped

    depends_on:
     database:
        condition: service_healthy

    environment:
      INSTANCE_NAME: "app2"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_NAME: "photo_archive"
      DB_USER: "aegean"
      DB_PASSWORD: "aegean"
      PYTHONUNBUFFERED: "1"

    ports:
      - "5002:5000"

    networks:
      - aegean-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped

    depends_on:
      - app1
      - app2

    ports:
      - "8080:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - aegean-network

volumes:
  mariadb-data:

networks:
  aegean-network:
    driver: bridge